### PR TITLE
Third-party-less lockin escrow

### PR DESCRIPTION
**Pull request by o-jasper**
Has a minor modification to `block.run` so that `run_tx` could provide the `method_name`. All the tests seem to still work.

Named it lockin-escrow because it locks in the funds if neither budges.

### CODE REVIEW

**Comment by jorisbontje** [comment]
Can you run `pep8` on this (I use `flake8` myself before committing)?

Using `random` for the tests is... interesting :) To make simulation runs deterministic I suggest setting `random.seed()`.

**Comment by o-jasper** [comment]
Yeah, maybe you should sometimes wait a bit before merging, as i sometimes get a little hasty.

Randomness does check more cases, randomly. Problem is that it currently doesnt remember the random state well, so you might not be able to repeat it. Dont think it often catches that many more cases, btw, going through different permutations of order of events would have a better shot and increasing the likelyhood of spotting mistakes. I dont think the combinatorial explosion is fast enough to prevent us from trying all permutations,(until contracts get complex) but how to code that efficiently...

**Comment by jorisbontje** [comment]
[Fuzz Testing](https://en.wikipedia.org/wiki/Fuzz_testing); there are various existing frameworks for that that might inspire you?

**Comment by jorisbontje** [comment]
BTW thanks for the fixes, looks beautiful now :)

**Comment by o-jasper** [comment]
Think I should probably add checking of `contract.txs`, to narrow that down better.

**Comment by jorisbontje** [comment]
Let me know if you think this can be merged or work on the `contract.txs` checks first

**Comment by o-jasper** [comment]
`contract.txs` checked now, can probably merge. I noticed that `max` had to be `min`

[Thought about testing a bit more.](https://github.com/jorisbontje/cll-sim/issues/10)

Btw, the fact that there is a `contract.storage[I_PAID]` and a `contract.balance`(though you cant ask for it that way for the latter) is a bit redundant, it could be done if [balances where](https://github.com/jorisbontje/cll-sim/issues/9)

**Comment by jorisbontje** [comment]
Merged! Nice work, thanks for sharing these more elaborate contracts

**Pull request merged**
